version: '3.4'
services:
  orleans-client:
    image: thewindev/crybot-client
    build:
      context: .
      dockerfile: Dockerfile
    volumes: 
      - ./CryBot.Web/bin/Release/netcoreapp2.1/publish:/app
      - ~/.nuget/packages:/root/.nuget/packages:ro
    depends_on: 
      - orleans-silo
  orleans-silo:
    image: thewindev/crybot-silo
    build:
      context: .
      dockerfile: Dockerfile
    volumes: 
      - ./CryBot.Silo/bin/Release/netcoreapp2.1/publish:/app
      - ~/.nuget/packages:/root/.nuget/packages:ro